# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: signserver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10signserver.proto\x12\nsignserver\"C\n\x0eRsaSignRequest\x12\x10\n\x08hash_str\x18\x01 \x01(\t\x12\x0f\n\x07key_set\x18\x02 \x01(\x05\x12\x0e\n\x06key_id\x18\x03 \x01(\x05\"!\n\x0cRsaSignReply\x12\x11\n\tsignature\x18\x01 \x01(\t\"E\n\x10RsaPubkeyRequest\x12\x0f\n\x07key_set\x18\x01 \x01(\x05\x12\x0e\n\x06key_id\x18\x02 \x01(\x05\x12\x10\n\x08key_type\x18\x03 \x01(\x05\"$\n\x0eRsaPubkeyReply\x12\x12\n\npublic_key\x18\x01 \x01(\t2\xa7\x01\n\x0b\x43odeSigning\x12I\n\x0fGetRsaSignature\x12\x1a.signserver.RsaSignRequest\x1a\x18.signserver.RsaSignReply\"\x00\x12M\n\x0fGetRsaPublicKey\x12\x1c.signserver.RsaPubkeyRequest\x1a\x1a.signserver.RsaPubkeyReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'signserver_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RSASIGNREQUEST']._serialized_start=32
  _globals['_RSASIGNREQUEST']._serialized_end=99
  _globals['_RSASIGNREPLY']._serialized_start=101
  _globals['_RSASIGNREPLY']._serialized_end=134
  _globals['_RSAPUBKEYREQUEST']._serialized_start=136
  _globals['_RSAPUBKEYREQUEST']._serialized_end=205
  _globals['_RSAPUBKEYREPLY']._serialized_start=207
  _globals['_RSAPUBKEYREPLY']._serialized_end=243
  _globals['_CODESIGNING']._serialized_start=246
  _globals['_CODESIGNING']._serialized_end=413
# @@protoc_insertion_point(module_scope)
